server:
  port: 8081
spring:
  application:
    name: bogeplus-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost
        port: 8848
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.230.36:3306/message?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: rw_user
    password: 12345678
#redis
  redis:
    host: 119.3.230.36  # Redis服务器地址
    port: 6379       # Redis服务器端口
    password: Aa123123123       # 如果Redis设置了密码，在这里填入
    timeout: 60000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 8        # 连接池中的最大连接数（使用负值表示没有限制）
        max-idle: 8          # 连接池中的最大空闲连接数
        min-idle: 0          # 连接池中的最小空闲连接数
        max-wait: -1ms       # 连接池获取连接时的最大等待时间
#mybatisPlus 的日志 推荐打开
# 稍后将mapper的 debug日志放在这里
mybatis-plus:
  logging:
    level:
      com.baomidou.mybatisplus: debug  # 开启 MyBatis-Plus 调试日志
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"  # 设置日志输出格式